"""core data model: sales, purchases, transactions, claims, whitelist, referral rewards, audit logs, notifications, settings

Revision ID: fcb02142d0b6
Revises: c08f318a3065
Create Date: 2026-08-24 23:42:57.739369
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'fcb02142d0b6'
down_revision: str | None = 'c08f318a3065'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('settings',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='uq_settings_user_id_key')
    )
    op.create_index(op.f('ix_settings_user_id'), 'settings', ['user_id'], unique=False)
    op.create_index('uq_settings_global_key', 'settings', ['key'], unique=True, postgresql_where=sa.text('user_id IS NULL'))
    op.create_table('transactions',
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('tx_hash', sa.String(length=66), nullable=True),
    sa.Column('status', sa.Enum('pending', 'submitted', 'confirmed', 'failed', name='transaction_status'), server_default='pending', nullable=False),
    sa.Column('related_user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['related_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_chain_id'), 'transactions', ['chain_id'], unique=False)
    op.create_index(op.f('ix_transactions_related_user_id'), 'transactions', ['related_user_id'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index('uq_transactions_chain_id_tx_hash', 'transactions', ['chain_id', 'tx_hash'], unique=True, postgresql_where=sa.text('tx_hash IS NOT NULL'))
    op.create_table('sales',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'scheduled', 'active', 'ended', 'cancelled', name='sale_status'), server_default='draft', nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hard_cap', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('soft_cap', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('price', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('min_contribution', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('max_contribution', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_at IS NULL OR start_at IS NULL OR end_at > start_at', name='ck_sales_end_after_start'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_project_id'), 'sales', ['project_id'], unique=False)
    op.create_index(op.f('ix_sales_status'), 'sales', ['status'], unique=False)
    op.create_table('claims',
    sa.Column('sale_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('allocated_amount', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('claimed_amount', sa.Numeric(precision=38, scale=18), server_default='0', nullable=False),
    sa.Column('status', sa.Enum('not_started', 'partially_claimed', 'fully_claimed', name='claim_status'), server_default='not_started', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sale_id', 'user_id', name='uq_claims_sale_id_user_id')
    )
    op.create_index(op.f('ix_claims_sale_id'), 'claims', ['sale_id'], unique=False)
    op.create_index(op.f('ix_claims_user_id'), 'claims', ['user_id'], unique=False)
    op.create_table('purchases',
    sa.Column('sale_id', sa.UUID(), nullable=False),
    sa.Column('purchaser_user_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'failed', name='purchase_status'), server_default='pending', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['purchaser_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchases_purchaser_user_id'), 'purchases', ['purchaser_user_id'], unique=False)
    op.create_index(op.f('ix_purchases_sale_id'), 'purchases', ['sale_id'], unique=False)
    op.create_index(op.f('ix_purchases_status'), 'purchases', ['status'], unique=False)
    op.create_table('referral_rewards',
    sa.Column('referrer_user_id', sa.UUID(), nullable=False),
    sa.Column('referred_user_id', sa.UUID(), nullable=False),
    sa.Column('sale_id', sa.UUID(), nullable=True),
    sa.Column('reward_amount', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'paid', name='referral_reward_status'), server_default='pending', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('referrer_user_id != referred_user_id', name='ck_referral_rewards_no_self_referral'),
    sa.ForeignKeyConstraint(['referred_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referrer_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_rewards_referred_user_id'), 'referral_rewards', ['referred_user_id'], unique=False)
    op.create_index(op.f('ix_referral_rewards_referrer_user_id'), 'referral_rewards', ['referrer_user_id'], unique=False)
    op.create_table('whitelist_entries',
    sa.Column('sale_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('allocation_cap', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sale_id', 'user_id', name='uq_whitelist_entries_sale_id_user_id')
    )
    op.create_index(op.f('ix_whitelist_entries_sale_id'), 'whitelist_entries', ['sale_id'], unique=False)
    op.create_index(op.f('ix_whitelist_entries_user_id'), 'whitelist_entries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whitelist_entries_user_id'), table_name='whitelist_entries')
    op.drop_index(op.f('ix_whitelist_entries_sale_id'), table_name='whitelist_entries')
    op.drop_table('whitelist_entries')
    op.drop_index(op.f('ix_referral_rewards_referrer_user_id'), table_name='referral_rewards')
    op.drop_index(op.f('ix_referral_rewards_referred_user_id'), table_name='referral_rewards')
    op.drop_table('referral_rewards')
    op.drop_index(op.f('ix_purchases_status'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_sale_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_purchaser_user_id'), table_name='purchases')
    op.drop_table('purchases')
    op.drop_index(op.f('ix_claims_user_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_sale_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_sales_status'), table_name='sales')
    op.drop_index(op.f('ix_sales_project_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_index('uq_transactions_chain_id_tx_hash', table_name='transactions', postgresql_where=sa.text('tx_hash IS NOT NULL'))
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_related_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_chain_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('uq_settings_global_key', table_name='settings', postgresql_where=sa.text('user_id IS NULL'))
    op.drop_index(op.f('ix_settings_user_id'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###

    # NOT auto-generated: Alembic's autogenerate drops the TABLES that use
    # a Postgres native enum type but does not drop the TYPE itself -- the
    # type has an independent lifecycle in Postgres. Left unfixed, a
    # downgrade followed by a re-upgrade fails with
    # `DuplicateObjectError: type "..." already exists`, because upgrade()
    # tries to CREATE TYPE for a type that downgrade() never dropped.
    # Order matters: these must run after every table that used them has
    # already been dropped above.
    sa.Enum(name='referral_reward_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='claim_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='purchase_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='sale_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='transaction_status').drop(op.get_bind(), checkfirst=True)
